/run/verbose 0
/tracking/verbose 0
/hits/verbose 0
/grdm/verbose 0

# Reproducible random seed.
/WCSim/random/generator HEPJAMES
/WCSim/random/seed 1

# Detector geometry.
/WCSim/WCgeom HyperK_HybridmPMT_WithOD_Realistic
/WCSim/Construct

# PMT response.
/WCSim/PMTQEMethod SensitiveDetector_Only
/WCSim/PMTCollEff on
/WCSim/SavePi0 false

# Digitizer and trigger.
/DAQ/Digitizer SKI
/DAQ/Trigger NDigits

/DAQ/DigitizerOpt/DeadTime 560 ns
/DAQ/DigitizerOpt/IntegrationWindow 200 ns
/DAQ/DigitizerOpt/TimingPrecision 0.1 ns
/DAQ/DigitizerOpt/PEPrecision 0.3

/DAQ/MultiDigitsPerTrigger true
/DAQ/TriggerSaveFailures/Mode 0

/DAQ/TriggerNDigits/Threshold 25
/DAQ/TriggerNDigits/AdjustForNoise true
/DAQ/TriggerNDigits/Window 200 ns
/DAQ/TriggerNDigits/PreTriggerWindow -400 ns
/DAQ/TriggerNDigits/PostTriggerWindow 950 ns

# Dark noise: 20-inch ID PMTs.
/DarkRate/SetDetectorElement tank
/DarkRate/SetDarkRate 4.2 kHz
/DarkRate/SetConvert 1.1125
/DarkRate/SetDarkMode 1
/DarkRate/SetDarkWindow 4000

# Dark noise: OD.
/DarkRate/SetDetectorElement OD
/DarkRate/SetDarkRate 1.0 kHz
/DarkRate/SetConvert 1.3554
/DarkRate/SetDarkMode 1
/DarkRate/SetDarkWindow 4000

# Dark noise: mPMTs.
/DarkRate/SetDetectorElement tankPMT2
/DarkRate/SetDarkRate 1.0 kHz
/DarkRate/SetConvert 1.1096
/DarkRate/SetDarkMode 1
/DarkRate/SetDarkWindow 4000

# Muon properties.
/particle/select mu+
/particle/property/stable false
/particle/property/lifetime 0.5 us

# GPS generator.
/mygen/generator gps
/gps/particle mu+

# Kinetic energy: uniform distribution.
/gps/ene/type Lin
/gps/ene/intercept 1
/gps/ene/min 54.6 MeV
/gps/ene/max 1554.6 MeV

# Isotropic direction.
/gps/ang/type iso

# Uniform vertex distribution inside HKFD ID.
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/halfz 3290 cm
/gps/pos/radius 3240 cm

# Output.
/WCSimIO/RootFile /home/users/montanel/HyperKamiokande/containers/data/WCSim_data/muplus_michel_Tau500ns_WCSim.root

# One event.
/run/beamOn 1